import productImg from "../../../public/productImg.png"

const products = [
  {
    id: 1,
    image: productImg,
    name: "Moog Synthesizer",
    category: "Electronics",
    price: "468.00",
    made_city: "Istanbul / Turkey",
  },
  {
    id: 2,
    image: productImg,
    name: "Moog Synthesizer",
    category: "Electronics",
    price: "468.00",
    made_city: "Istanbul / Turkey",
  },
  {
    id: 3,
    image: productImg,
    name: "Moog Synthesizer",
    category: "Electronics",
    price: "468.00",
    made_city: "Istanbul / Turkey",
  },
  {
    id: 4,
    image: productImg,
    name: "Moog Synthesizer",
    category: "Electronics",
    price: "468.00",
    made_city: "Istanbul / Turkey",
  },
  {
    id: 5,
    image: productImg,
    name: "Moog Synthesizer",
    category: "Electronics",
    price: "468.00",
    made_city: "Istanbul / Turkey",
  },
  {
    id: 5,
    image: productImg,
    name: "Moog Synthesizer",
    category: "Electronics",
    price: "468.00",
    made_city: "Istanbul / Turkey",
  },
  {
    id: 5,
    image: productImg,
    name: "Moog Synthesizer",
    category: "Electronics",
    price: "468.00",
    made_city: "Istanbul / Turkey",
  },
  {
    id: 5,
    image: productImg,
    name: "Moog Synthesizer",
    category: "Electronics",
    price: "468.00",
    made_city: "Istanbul / Turkey",
  },
  {
    id: 5,
    image: productImg,
    name: "Moog Synthesizer",
    category: "Electronics",
    price: "468.00",
    made_city: "Istanbul / Turkey",
  },
  {
    id: 5,
    image: productImg,
    name: "Moog Synthesizer",
    category: "Electronics",
    price: "468.00",
    made_city: "Istanbul / Turkey",
  },
  {
    id: 5,
    image: productImg,
    name: "Moog Synthesizer",
    category: "Electronics",
    price: "468.00",
    made_city: "Istanbul / Turkey",
  },
  {
    id: 5,
    image: productImg,
    name: "Moog Synthesizer",
    category: "Electronics",
    price: "468.00",
    made_city: "Istanbul / Turkey",
  },
  {
    id: 5,
    image: productImg,
    name: "Moog Synthesizer",
    category: "Electronics",
    price: "468.00",
    made_city: "Istanbul / Turkey",
  },
  {
    id: 5,
    image: productImg,
    name: "Moog Synthesizer",
    category: "Electronics",
    price: "468.00",
    made_city: "Istanbul / Turkey",
  },
  {
    id: 5,
    image: productImg,
    name: "Moog Synthesizer",
    category: "Electronics",
    price: "468.00",
    made_city: "Istanbul / Turkey",
  },
  {
    id: 5,
    image: productImg,
    name: "Moog Synthesizer",
    category: "Electronics",
    price: "468.00",
    made_city: "Istanbul / Turkey",
  },
]

export default products
