import { withTranslation } from "next-i18next"

const products = [
  {
    id: 1,
    name: "Moog Synthesizer",
    category: "Books",
    price: 10.0,
    made_city: "Istanbul / Turkey",
    order_date: "01/04/2023",
    listing_date: "25/2/2023",
    delivery_address: "X Apartment Y Street Z Province Istanbul/Turkey",
    images: "/images/productImg.png",
  },
  {
    id: 2,
    name: "Moog Synthesizer",
    category: "Furniture",
    price: 20.0,
    made_city: "Istanbul / Turkey",
    order_date: "03/04/2023",
    listing_date: "25/2/2023",
    delivery_address: "X Apartment Y Street Z Province Istanbul/Turkey",
    images: "/images/productImg.png",
  },
  {
    id: 3,
    name: "Moog Synthesizer",
    category: "Furniture",
    price: 30.0,
    made_city: "Istanbul / Turkey",
    order_date: "05/04/2023",
    listing_date: "25/2/2023",
    delivery_address: "X Apartment Y Street Z Province Istanbul/Turkey",
    images: "/images/productImg.png",
  },
  {
    id: 4,
    name: "Moog Synthesizer",
    category: "Electronics",
    price: 40.0,
    made_city: "Istanbul / Turkey",
    order_date: "07/04/2023",
    listing_date: "25/2/2023",
    delivery_address: "X Apartment Y Street Z Province Istanbul/Turkey",
    images: "/images/productImg.png",
  },
  {
    id: 5,
    name: "Moog Synthesizer",
    category: "Two-wheeler",
    price: 50.0,
    made_city: "Istanbul / Turkey",
    order_date: "09/04/2023",
    listing_date: "25/2/2023",
    delivery_address: "X Apartment Y Street Z Province Istanbul/Turkey",
    images: "/images/productImg.png",
  },
  {
    id: 6,
    name: "Moog Synthesizer",
    category: "Two-wheeler",
    price: 60.0,
    made_city: "Istanbul / Turkey",
    order_date: "11/04/2023",
    listing_date: "25/2/2023",
    delivery_address: "X Apartment Y Street Z Province Istanbul/Turkey",
    images: "/images/productImg.png",
  },
  {
    id: 7,
    name: "Moog Synthesizer",
    category: "Two-wheeler",
    price: 70.0,
    made_city: "Istanbul / Turkey",
    order_date: "13/04/2023",
    listing_date: "25/2/2023",
    delivery_address: "X Apartment Y Street Z Province Istanbul/Turkey",
    images: "/images/productImg.png",
  },
  {
    id: 8,
    name: "Moog Synthesizer",
    category: "Two-wheeler",
    price: 80.0,
    made_city: "Istanbul / Turkey",
    order_date: "15/04/2023",
    listing_date: "25/2/2023",
    delivery_address: "X Apartment Y Street Z Province Istanbul/Turkey",
    images: "/images/productImg.png",
  },
  {
    id: 9,
    name: "Moog Synthesizer",
    category: "Two-wheeler",
    price: 90.0,
    made_city: "Istanbul / Turkey",
    order_date: "17/04/2023",
    listing_date: "25/2/2023",
    delivery_address: "X Apartment Y Street Z Province Istanbul/Turkey",
    images: "/images/productImg.png",
  },
  {
    id: 10,
    name: "Moog Synthesizer",
    category: "Two-wheeler",
    price: 100.0,
    made_city: "Istanbul / Turkey",
    order_date: "19/04/2023",
    listing_date: "25/2/2023",
    delivery_address: "X Apartment Y Street Z Province Istanbul/Turkey",
    images: "/images/productImg.png",
  },
  {
    id: 11,
    name: "Moog Synthesizer",
    category: "Electronics",
    price: 200.0,
    made_city: "Istanbul / Turkey",
    order_date: "21/04/2023",
    listing_date: "25/2/2023",
    delivery_address: "X Apartment Y Street Z Province Istanbul/Turkey",
    images: "/images/productImg.png",
  },
  {
    id: 12,
    name: "Moog Synthesizer",
    category: "Electronics",
    price: 300.0,
    made_city: "Istanbul / Turkey",
    order_date: "23/04/2023",
    listing_date: "25/2/2023",
    delivery_address: "X Apartment Y Street Z Province Istanbul/Turkey",
    images: "/images/productImg.png",
  },
  {
    id: 13,
    name: "Moog Synthesizer",
    category: "Electronics",
    price: 500.0,
    made_city: "Istanbul / Turkey",
    order_date: "25/04/2023",
    listing_date: "25/2/2023",
    delivery_address: "X Apartment Y Street Z Province Istanbul/Turkey",
    images: "/images/productImg.png",
  },
  {
    id: 14,
    name: "Moog Synthesizer",
    category: "Electronics",
    price: 600.0,
    made_city: "Istanbul / Turkey",
    order_date: "27/04/2023",
    listing_date: "25/2/2023",
    delivery_address: "X Apartment Y Street Z Province Istanbul/Turkey",
    images: "/images/productImg.png",
  },
  {
    id: 15,
    name: "Moog Synthesizer",
    category: "Electronics",
    price: 700.0,
    made_city: "Istanbul / Turkey",
    order_date: "01/05/2023",
    listing_date: "25/2/2023",
    delivery_address: "X Apartment Y Street Z Province Istanbul/Turkey",
    images: "/images/productImg.png",
  },
  {
    id: 16,
    name: "Moog Synthesizer",
    category: "Electronics",
    price: 800.0,
    made_city: "Istanbul / Turkey",
    order_date: "03/05/2023",
    listing_date: "25/2/2023",
    delivery_address: "X Apartment Y Street Z Province Istanbul/Turkey",
    images: "/images/productImg.png",
  },
]

export default withTranslation("index")(products)
