function Products({ t }) {
  const product = [
    {
      id: 1,
      name: t("name-product"),
      category: t("filter-one"),
      price: 10.0,
      made_city: t("made-city"),
      order_date: "01/04/2023",
      listing_date: "25/2/2023",
      delivery_address: "X Apartment Y Street Z Province Istanbul/Turkey",
      images: "/images/productImg.png",
    },
    {
      id: 2,
      name: t("name-product"),
      category: t("filter-two"),
      price: 20.0,
      made_city: t("made-city"),
      order_date: "03/04/2023",
      listing_date: "25/2/2023",
      delivery_address: "X Apartment Y Street Z Province Istanbul/Turkey",
      images: "/images/productImg.png",
    },
    {
      id: 3,
      name: t("name-product"),
      category: t("filter-two"),
      price: 30.0,
      made_city: t("made-city"),
      order_date: "05/04/2023",
      listing_date: "25/2/2023",
      delivery_address: "X Apartment Y Street Z Province Istanbul/Turkey",
      images: "/images/productImg.png",
    },
    {
      id: 4,
      name: t("name-product"),
      category: t("filter-three"),
      price: 40.0,
      made_city: t("made-city"),
      order_date: "07/04/2023",
      listing_date: "25/2/2023",
      delivery_address: "X Apartment Y Street Z Province Istanbul/Turkey",
      images: "/images/productImg.png",
    },
    {
      id: 5,
      name: t("name-product"),
      category: t("filter-four"),
      price: 50.0,
      made_city: t("made-city"),
      order_date: "09/04/2023",
      listing_date: "25/2/2023",
      delivery_address: "X Apartment Y Street Z Province Istanbul/Turkey",
      images: "/images/productImg.png",
    },
    {
      id: 6,
      name: t("name-product"),
      category: t("filter-four"),
      price: 60.0,
      made_city: t("made-city"),
      order_date: "11/04/2023",
      listing_date: "25/2/2023",
      delivery_address: "X Apartment Y Street Z Province Istanbul/Turkey",
      images: "/images/productImg.png",
    },
    {
      id: 7,
      name: t("name-product"),
      category: t("filter-four"),
      price: 70.0,
      made_city: t("made-city"),
      order_date: "13/04/2023",
      listing_date: "25/2/2023",
      delivery_address: "X Apartment Y Street Z Province Istanbul/Turkey",
      images: "/images/productImg.png",
    },
    {
      id: 8,
      name: t("name-product"),
      category: t("filter-four"),
      price: 80.0,
      made_city: t("made-city"),
      order_date: "15/04/2023",
      listing_date: "25/2/2023",
      delivery_address: "X Apartment Y Street Z Province Istanbul/Turkey",
      images: "/images/productImg.png",
    },
    {
      id: 9,
      name: t("name-product"),
      category: t("filter-four"),
      price: 90.0,
      made_city: t("made-city"),
      order_date: "17/04/2023",
      listing_date: "25/2/2023",
      delivery_address: "X Apartment Y Street Z Province Istanbul/Turkey",
      images: "/images/productImg.png",
    },
    {
      id: 10,
      name: t("name-product"),
      category: t("filter-four"),
      price: 100.0,
      made_city: t("made-city"),
      order_date: "19/04/2023",
      listing_date: "25/2/2023",
      delivery_address: "X Apartment Y Street Z Province Istanbul/Turkey",
      images: "/images/productImg.png",
    },
    {
      id: 11,
      name: t("name-product"),
      category: t("filter-three"),
      price: 200.0,
      made_city: t("made-city"),
      order_date: "21/04/2023",
      listing_date: "25/2/2023",
      delivery_address: "X Apartment Y Street Z Province Istanbul/Turkey",
      images: "/images/productImg.png",
    },
    {
      id: 12,
      name: t("name-product"),
      category: t("filter-three"),
      price: 300.0,
      made_city: t("made-city"),
      order_date: "23/04/2023",
      listing_date: "25/2/2023",
      delivery_address: "X Apartment Y Street Z Province Istanbul/Turkey",
      images: "/images/productImg.png",
    },
    {
      id: 13,
      name: t("name-product"),
      category: t("filter-three"),
      price: 500.0,
      made_city: t("made-city"),
      order_date: "25/04/2023",
      listing_date: "25/2/2023",
      delivery_address: "X Apartment Y Street Z Province Istanbul/Turkey",
      images: "/images/productImg.png",
    },
    {
      id: 14,
      name: t("name-product"),
      category: t("filter-three"),
      price: 600.0,
      made_city: t("made-city"),
      order_date: "27/04/2023",
      listing_date: "25/2/2023",
      delivery_address: "X Apartment Y Street Z Province Istanbul/Turkey",
      images: "/images/productImg.png",
    },
    {
      id: 15,
      name: t("name-product"),
      category: t("filter-three"),
      price: 700.0,
      made_city: t("made-city"),
      order_date: "01/05/2023",
      listing_date: "25/2/2023",
      delivery_address: "X Apartment Y Street Z Province Istanbul/Turkey",
      images: "/images/productImg.png",
    },
    {
      id: 16,
      name: t("name-product"),
      category: t("filter-three"),
      price: 800.0,
      made_city: t("made-city"),
      order_date: "03/05/2023",
      listing_date: "25/2/2023",
      delivery_address: "X Apartment Y Street Z Province Istanbul/Turkey",
      images: "/images/productImg.png",
    },
  ]

  return product
}

export default Products
